"""Initial Revision

Revision ID: bbb2c9df52a9
Revises: 
Create Date: 2018-04-22 13:25:06.933093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb2c9df52a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('line_1', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('line_2', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('line_3', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('region', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_address_version_end_transaction_id'), 'address_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_address_version_operation_type'), 'address_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_address_version_transaction_id'), 'address_version', ['transaction_id'], unique=False)
    op.create_table('admission_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('bed_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('discharged_bed_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('hospital_course', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('discharge_advice', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('follow_up', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('complication_grade_id', sa.String(length=5), autoincrement=False, nullable=True),
    sa.Column('complication_summary', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('complication_disability', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_admission_version_end_transaction_id'), 'admission_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_admission_version_operation_type'), 'admission_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_admission_version_transaction_id'), 'admission_version', ['transaction_id'], unique=False)
    op.create_table('circumcisionadmission_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('preoperative_orders', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_circumcisionadmission_version_end_transaction_id'), 'circumcisionadmission_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_circumcisionadmission_version_operation_type'), 'circumcisionadmission_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_circumcisionadmission_version_transaction_id'), 'circumcisionadmission_version', ['transaction_id'], unique=False)
    op.create_table('clinicalencounter_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('chief_complaints', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('history', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('past_history', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('general_inspection', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_head', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_neck', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_chest', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_abdomen', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_genitalia', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_pelvic_rectal', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_extremities', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('exam_other', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('written_by', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_clinicalencounter_version_end_transaction_id'), 'clinicalencounter_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_clinicalencounter_version_operation_type'), 'clinicalencounter_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_clinicalencounter_version_transaction_id'), 'clinicalencounter_version', ['transaction_id'], unique=False)
    op.create_table('completebloodcount_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('hemoglobin', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('tlc', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('plt', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('dlc_n', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('dlc_l', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('dlc_m', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('dlc_e', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_completebloodcount_version_end_transaction_id'), 'completebloodcount_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_completebloodcount_version_operation_type'), 'completebloodcount_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_completebloodcount_version_transaction_id'), 'completebloodcount_version', ['transaction_id'], unique=False)
    op.create_table('encounter_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('personnel_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_encounter_version_end_transaction_id'), 'encounter_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_encounter_version_operation_type'), 'encounter_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_encounter_version_transaction_id'), 'encounter_version', ['transaction_id'], unique=False)
    op.create_table('endoscopy_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('site', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('report', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('impression', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('endoscopist', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_endoscopy_version_end_transaction_id'), 'endoscopy_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_endoscopy_version_operation_type'), 'endoscopy_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_endoscopy_version_transaction_id'), 'endoscopy_version', ['transaction_id'], unique=False)
    op.create_table('histopathology_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('site', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('report', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('impression', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('pathologist', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_histopathology_version_end_transaction_id'), 'histopathology_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_histopathology_version_operation_type'), 'histopathology_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_histopathology_version_transaction_id'), 'histopathology_version', ['transaction_id'], unique=False)
    op.create_table('imaging_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('site', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('imaging_type', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('report', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('impression', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('radiologist', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_imaging_version_end_transaction_id'), 'imaging_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_imaging_version_operation_type'), 'imaging_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_imaging_version_transaction_id'), 'imaging_version', ['transaction_id'], unique=False)
    op.create_table('investigation_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_investigation_version_end_transaction_id'), 'investigation_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_investigation_version_operation_type'), 'investigation_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_investigation_version_transaction_id'), 'investigation_version', ['transaction_id'], unique=False)
    op.create_table('liverfunctiontest_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('t_bil', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('d_bil', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('alt', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('ast', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('alp', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_liverfunctiontest_version_end_transaction_id'), 'liverfunctiontest_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_liverfunctiontest_version_operation_type'), 'liverfunctiontest_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_liverfunctiontest_version_transaction_id'), 'liverfunctiontest_version', ['transaction_id'], unique=False)
    op.create_table('measurements_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('height', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_measurements_version_end_transaction_id'), 'measurements_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_measurements_version_operation_type'), 'measurements_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_measurements_version_transaction_id'), 'measurements_version', ['transaction_id'], unique=False)
    op.create_table('otherencounter_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('note', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_otherencounter_version_end_transaction_id'), 'otherencounter_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_otherencounter_version_operation_type'), 'otherencounter_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_otherencounter_version_transaction_id'), 'otherencounter_version', ['transaction_id'], unique=False)
    op.create_table('otherreport_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('report', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('impression', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('reported_by', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_otherreport_version_end_transaction_id'), 'otherreport_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_otherreport_version_operation_type'), 'otherreport_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_otherreport_version_transaction_id'), 'otherreport_version', ['transaction_id'], unique=False)
    op.create_table('othertest_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('value', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('unit', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_othertest_version_end_transaction_id'), 'othertest_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_othertest_version_operation_type'), 'othertest_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_othertest_version_transaction_id'), 'othertest_version', ['transaction_id'], unique=False)
    op.create_table('outpatientencounter_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('room', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_outpatientencounter_version_end_transaction_id'), 'outpatientencounter_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_outpatientencounter_version_operation_type'), 'outpatientencounter_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_outpatientencounter_version_transaction_id'), 'outpatientencounter_version', ['transaction_id'], unique=False)
    op.create_table('patient_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('hospital_no', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('national_id_no', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('time_of_birth', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('time_of_death', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.String(length=1), autoincrement=False, nullable=True),
    sa.Column('allergies', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('phone_no', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('permanent_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('current_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_patient_version_end_transaction_id'), 'patient_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_patient_version_operation_type'), 'patient_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_patient_version_transaction_id'), 'patient_version', ['transaction_id'], unique=False)
    op.create_table('prescription_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('clinicalencounter_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('drug_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('drug_order', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_prescription_version_end_transaction_id'), 'prescription_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_prescription_version_operation_type'), 'prescription_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_prescription_version_transaction_id'), 'prescription_version', ['transaction_id'], unique=False)
    op.create_table('problem_encounter_association_version',
    sa.Column('problem_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('encounter_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_problem_encounter_association_version_end_transaction_id'), 'problem_encounter_association_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_problem_encounter_association_version_operation_type'), 'problem_encounter_association_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_problem_encounter_association_version_transaction_id'), 'problem_encounter_association_version', ['transaction_id'], unique=False)
    op.create_table('problem_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('icd10class_code', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('icd10modifier_class_code', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('icd10modifier_extra_class_code', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_problem_version_end_transaction_id'), 'problem_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_problem_version_operation_type'), 'problem_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_problem_version_transaction_id'), 'problem_version', ['transaction_id'], unique=False)
    op.create_table('progress_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('subjective', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('objective', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('assessment', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_progress_version_end_transaction_id'), 'progress_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_progress_version_operation_type'), 'progress_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_progress_version_transaction_id'), 'progress_version', ['transaction_id'], unique=False)
    op.create_table('renalfunctiontest_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('urea', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('creatinine', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_renalfunctiontest_version_end_transaction_id'), 'renalfunctiontest_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_renalfunctiontest_version_operation_type'), 'renalfunctiontest_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_renalfunctiontest_version_transaction_id'), 'renalfunctiontest_version', ['transaction_id'], unique=False)
    op.create_table('surgicalprocedure_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('assistant', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('anesthetist', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('nurse', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('emergency', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('preoperative_diagnosis', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('postoperative_diagnosis', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('procedure_name', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('findings', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('steps', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_surgicalprocedure_version_end_transaction_id'), 'surgicalprocedure_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_surgicalprocedure_version_operation_type'), 'surgicalprocedure_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_surgicalprocedure_version_transaction_id'), 'surgicalprocedure_version', ['transaction_id'], unique=False)
    op.create_table('vitalsigns_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('pulse_rate', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('respiratory_rate', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('diastolic_bp', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('systolic_bp', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_vitalsigns_version_end_transaction_id'), 'vitalsigns_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_vitalsigns_version_operation_type'), 'vitalsigns_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_vitalsigns_version_transaction_id'), 'vitalsigns_version', ['transaction_id'], unique=False)
    op.create_table('vitalsignsextended_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('cvp', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('systolic_ibp', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('diastolic_ibp', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('cap_spo2', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_vitalsignsextended_version_end_transaction_id'), 'vitalsignsextended_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_vitalsignsextended_version_operation_type'), 'vitalsignsextended_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_vitalsignsextended_version_transaction_id'), 'vitalsignsextended_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.drop_table('presetprescription')
    op.drop_table('presetmedication')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presetmedication',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('preset_id', sa.INTEGER(), nullable=True),
    sa.Column('drug_id', sa.INTEGER(), nullable=True),
    sa.Column('drug_order', sa.VARCHAR(length=250), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['presetprescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presetprescription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_vitalsignsextended_version_transaction_id'), table_name='vitalsignsextended_version')
    op.drop_index(op.f('ix_vitalsignsextended_version_operation_type'), table_name='vitalsignsextended_version')
    op.drop_index(op.f('ix_vitalsignsextended_version_end_transaction_id'), table_name='vitalsignsextended_version')
    op.drop_table('vitalsignsextended_version')
    op.drop_index(op.f('ix_vitalsigns_version_transaction_id'), table_name='vitalsigns_version')
    op.drop_index(op.f('ix_vitalsigns_version_operation_type'), table_name='vitalsigns_version')
    op.drop_index(op.f('ix_vitalsigns_version_end_transaction_id'), table_name='vitalsigns_version')
    op.drop_table('vitalsigns_version')
    op.drop_index(op.f('ix_surgicalprocedure_version_transaction_id'), table_name='surgicalprocedure_version')
    op.drop_index(op.f('ix_surgicalprocedure_version_operation_type'), table_name='surgicalprocedure_version')
    op.drop_index(op.f('ix_surgicalprocedure_version_end_transaction_id'), table_name='surgicalprocedure_version')
    op.drop_table('surgicalprocedure_version')
    op.drop_index(op.f('ix_renalfunctiontest_version_transaction_id'), table_name='renalfunctiontest_version')
    op.drop_index(op.f('ix_renalfunctiontest_version_operation_type'), table_name='renalfunctiontest_version')
    op.drop_index(op.f('ix_renalfunctiontest_version_end_transaction_id'), table_name='renalfunctiontest_version')
    op.drop_table('renalfunctiontest_version')
    op.drop_index(op.f('ix_progress_version_transaction_id'), table_name='progress_version')
    op.drop_index(op.f('ix_progress_version_operation_type'), table_name='progress_version')
    op.drop_index(op.f('ix_progress_version_end_transaction_id'), table_name='progress_version')
    op.drop_table('progress_version')
    op.drop_index(op.f('ix_problem_version_transaction_id'), table_name='problem_version')
    op.drop_index(op.f('ix_problem_version_operation_type'), table_name='problem_version')
    op.drop_index(op.f('ix_problem_version_end_transaction_id'), table_name='problem_version')
    op.drop_table('problem_version')
    op.drop_index(op.f('ix_problem_encounter_association_version_transaction_id'), table_name='problem_encounter_association_version')
    op.drop_index(op.f('ix_problem_encounter_association_version_operation_type'), table_name='problem_encounter_association_version')
    op.drop_index(op.f('ix_problem_encounter_association_version_end_transaction_id'), table_name='problem_encounter_association_version')
    op.drop_table('problem_encounter_association_version')
    op.drop_index(op.f('ix_prescription_version_transaction_id'), table_name='prescription_version')
    op.drop_index(op.f('ix_prescription_version_operation_type'), table_name='prescription_version')
    op.drop_index(op.f('ix_prescription_version_end_transaction_id'), table_name='prescription_version')
    op.drop_table('prescription_version')
    op.drop_index(op.f('ix_patient_version_transaction_id'), table_name='patient_version')
    op.drop_index(op.f('ix_patient_version_operation_type'), table_name='patient_version')
    op.drop_index(op.f('ix_patient_version_end_transaction_id'), table_name='patient_version')
    op.drop_table('patient_version')
    op.drop_index(op.f('ix_outpatientencounter_version_transaction_id'), table_name='outpatientencounter_version')
    op.drop_index(op.f('ix_outpatientencounter_version_operation_type'), table_name='outpatientencounter_version')
    op.drop_index(op.f('ix_outpatientencounter_version_end_transaction_id'), table_name='outpatientencounter_version')
    op.drop_table('outpatientencounter_version')
    op.drop_index(op.f('ix_othertest_version_transaction_id'), table_name='othertest_version')
    op.drop_index(op.f('ix_othertest_version_operation_type'), table_name='othertest_version')
    op.drop_index(op.f('ix_othertest_version_end_transaction_id'), table_name='othertest_version')
    op.drop_table('othertest_version')
    op.drop_index(op.f('ix_otherreport_version_transaction_id'), table_name='otherreport_version')
    op.drop_index(op.f('ix_otherreport_version_operation_type'), table_name='otherreport_version')
    op.drop_index(op.f('ix_otherreport_version_end_transaction_id'), table_name='otherreport_version')
    op.drop_table('otherreport_version')
    op.drop_index(op.f('ix_otherencounter_version_transaction_id'), table_name='otherencounter_version')
    op.drop_index(op.f('ix_otherencounter_version_operation_type'), table_name='otherencounter_version')
    op.drop_index(op.f('ix_otherencounter_version_end_transaction_id'), table_name='otherencounter_version')
    op.drop_table('otherencounter_version')
    op.drop_index(op.f('ix_measurements_version_transaction_id'), table_name='measurements_version')
    op.drop_index(op.f('ix_measurements_version_operation_type'), table_name='measurements_version')
    op.drop_index(op.f('ix_measurements_version_end_transaction_id'), table_name='measurements_version')
    op.drop_table('measurements_version')
    op.drop_index(op.f('ix_liverfunctiontest_version_transaction_id'), table_name='liverfunctiontest_version')
    op.drop_index(op.f('ix_liverfunctiontest_version_operation_type'), table_name='liverfunctiontest_version')
    op.drop_index(op.f('ix_liverfunctiontest_version_end_transaction_id'), table_name='liverfunctiontest_version')
    op.drop_table('liverfunctiontest_version')
    op.drop_index(op.f('ix_investigation_version_transaction_id'), table_name='investigation_version')
    op.drop_index(op.f('ix_investigation_version_operation_type'), table_name='investigation_version')
    op.drop_index(op.f('ix_investigation_version_end_transaction_id'), table_name='investigation_version')
    op.drop_table('investigation_version')
    op.drop_index(op.f('ix_imaging_version_transaction_id'), table_name='imaging_version')
    op.drop_index(op.f('ix_imaging_version_operation_type'), table_name='imaging_version')
    op.drop_index(op.f('ix_imaging_version_end_transaction_id'), table_name='imaging_version')
    op.drop_table('imaging_version')
    op.drop_index(op.f('ix_histopathology_version_transaction_id'), table_name='histopathology_version')
    op.drop_index(op.f('ix_histopathology_version_operation_type'), table_name='histopathology_version')
    op.drop_index(op.f('ix_histopathology_version_end_transaction_id'), table_name='histopathology_version')
    op.drop_table('histopathology_version')
    op.drop_index(op.f('ix_endoscopy_version_transaction_id'), table_name='endoscopy_version')
    op.drop_index(op.f('ix_endoscopy_version_operation_type'), table_name='endoscopy_version')
    op.drop_index(op.f('ix_endoscopy_version_end_transaction_id'), table_name='endoscopy_version')
    op.drop_table('endoscopy_version')
    op.drop_index(op.f('ix_encounter_version_transaction_id'), table_name='encounter_version')
    op.drop_index(op.f('ix_encounter_version_operation_type'), table_name='encounter_version')
    op.drop_index(op.f('ix_encounter_version_end_transaction_id'), table_name='encounter_version')
    op.drop_table('encounter_version')
    op.drop_index(op.f('ix_completebloodcount_version_transaction_id'), table_name='completebloodcount_version')
    op.drop_index(op.f('ix_completebloodcount_version_operation_type'), table_name='completebloodcount_version')
    op.drop_index(op.f('ix_completebloodcount_version_end_transaction_id'), table_name='completebloodcount_version')
    op.drop_table('completebloodcount_version')
    op.drop_index(op.f('ix_clinicalencounter_version_transaction_id'), table_name='clinicalencounter_version')
    op.drop_index(op.f('ix_clinicalencounter_version_operation_type'), table_name='clinicalencounter_version')
    op.drop_index(op.f('ix_clinicalencounter_version_end_transaction_id'), table_name='clinicalencounter_version')
    op.drop_table('clinicalencounter_version')
    op.drop_index(op.f('ix_circumcisionadmission_version_transaction_id'), table_name='circumcisionadmission_version')
    op.drop_index(op.f('ix_circumcisionadmission_version_operation_type'), table_name='circumcisionadmission_version')
    op.drop_index(op.f('ix_circumcisionadmission_version_end_transaction_id'), table_name='circumcisionadmission_version')
    op.drop_table('circumcisionadmission_version')
    op.drop_index(op.f('ix_admission_version_transaction_id'), table_name='admission_version')
    op.drop_index(op.f('ix_admission_version_operation_type'), table_name='admission_version')
    op.drop_index(op.f('ix_admission_version_end_transaction_id'), table_name='admission_version')
    op.drop_table('admission_version')
    op.drop_index(op.f('ix_address_version_transaction_id'), table_name='address_version')
    op.drop_index(op.f('ix_address_version_operation_type'), table_name='address_version')
    op.drop_index(op.f('ix_address_version_end_transaction_id'), table_name='address_version')
    op.drop_table('address_version')
    # ### end Alembic commands ###
